version: '3.8'

services:
  meshstorage-server:
    image: meshstorage-server:1.0.0
    container_name: meshstorage-server
    ports:
      - "3001:3001"
    env_file:
      - .env
    restart: unless-stopped
