version: "3.9"

services:
  meshstorage-frontend:
    image: meshstorage-frontend:1.0.0
    container_name: meshstorage-frontend.net
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Staging
      ApiSettings__BaseUrl: http://192.168.1.21:3001